import { AppProps } from 'next/app'
import Head from 'next/head'
import {MouseEventHandler, useState} from 'react'
import Menu from '../components/Menu'
import StyleGlobal from '../styles/StyleGlobal'


export default function MyApp({ Component, pageProps }: AppProps) {

    const [isDark, setisDark] = useState(false)
    const fondoColor:string = isDark? `rgb(0,0,35)` : `rgb(200,200,200)`
    const letraColor:string = isDark? `rgb(30,90,250)` : `rgb(125,0,0)`
    const anchorColor:string = isDark? "rgb(60, 180, 255)" : "rgb(200,75,75)"

    const handleClick: () => MouseEventHandler = function() : any {
        setisDark(!isDark)
    }
    

return (
<>
    <Head>
        <title>TwitterClone by ZitrojjDev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
     
   <Menu handleClick={handleClick} isDark={isDark} />

    <Component {...pageProps} />

    <footer >
        
    </footer>
    
    <Style anchorColor={anchorColor} letraColor={letraColor}/>
    <StyleGlobal fondoColor={fondoColor} letraColor={letraColor} anchorColor={anchorColor}/>

</>
)}
// practica personal?: los estilos que afectan el layout de un componente, se escriben en su componente padre. pero los atributos de color y forma se escriben en el propio componente?
interface Style {
    anchorColor:string;
    letraColor:string;
}

function Style({anchorColor, letraColor}:Style){
    return (
    <style jsx>{`
    
    a {
      color: ${anchorColor};
      text-decoration: none;
      padding: 0 0.3rem;
    }
  
    header {
      width:100%;
      height: 10vh;
      display: flex;
      flex-direction:row;
      align-items: center;
      border: 2px solid ${letraColor};
      border-radius: 10px
    }
    button {
      margin: auto 0.3rem;
    }
    footer {
      width:100%;
      height:10vh;
      position: fixed;
      bottom:0;
      background: red;
    }
  `}
    </style>
    )
  }
  
